baseurl      = "https://cv.snivou.com/"
languageCode = "en-us"
disableKinds = ["RSS", "sitemap", "404"]
theme = "hugo-pillar-theme"
#  Uncomment and provide valid UA-ID to enable GA
# googleAnalytics = "UA-XXXXXXX-Y"

#  See: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
    [privacy.googleAnalytics]
        anonymizeIP       = true
        respectDoNotTrack = true
        useSessionStorage = true

[params]
    author  = "snivou"
    title   = "My Resume"
    tagline = "My Resume"
    style   = "pillar-1.css"
